// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYzVZvjfOaCuOYWRJIOdGTpp03J3AZQco',
    appId: '1:35541229487:web:6a59e074753e77d399d95a',
    messagingSenderId: '35541229487',
    projectId: 'arsoudeserv',
    authDomain: 'arsoudeserv.firebaseapp.com',
    storageBucket: 'arsoudeserv.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClZwRgLS5zYt6bwdMxKn6gpHIfFwnREgs',
    appId: '1:35541229487:android:ae1e743f16dc839f99d95a',
    messagingSenderId: '35541229487',
    projectId: 'arsoudeserv',
    storageBucket: 'arsoudeserv.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCaisk8i2UB1uaqj57785DBUf5jwZKOp4k',
    appId: '1:35541229487:ios:6bfc9ad2fb208e3a99d95a',
    messagingSenderId: '35541229487',
    projectId: 'arsoudeserv',
    storageBucket: 'arsoudeserv.appspot.com',
    iosBundleId: 'PO.Arsoude.untitled',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCaisk8i2UB1uaqj57785DBUf5jwZKOp4k',
    appId: '1:35541229487:ios:81a58c3fc6800bbb99d95a',
    messagingSenderId: '35541229487',
    projectId: 'arsoudeserv',
    storageBucket: 'arsoudeserv.appspot.com',
    iosBundleId: 'PO.Arsoude.untitled.RunnerTests',
  );
}
